"""add effects to messages

Revision ID: 6ccbd5df4a0a
Revises: 8a0fa7c0ed8a
Create Date: 2026-03-17 00:47:14.546613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ccbd5df4a0a'
down_revision: Union[str, Sequence[str], None] = '8a0fa7c0ed8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('effect', sa.String(length=32), nullable=True))
    op.add_column('messages', sa.Column('effect_payload', sa.Text(), nullable=True))
    op.create_index(op.f('ix_messages_effect'), 'messages', ['effect'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_effect'), table_name='messages')
    op.drop_column('messages', 'effect_payload')
    op.drop_column('messages', 'effect')
    # ### end Alembic commands ###
