"""initial_recreation

Revision ID: 8a0fa7c0ed8a
Revises: 
Create Date: 2026-03-15 22:18:31.532619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a0fa7c0ed8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('archetype', sa.Enum('FOXY', 'OXY', 'BEAR', 'OWL', name='archetype'), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('charisma', sa.Float(), nullable=False),
    sa.Column('influence', sa.Float(), nullable=False),
    sa.Column('activity', sa.Float(), nullable=False),
    sa.Column('strategy', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('organization', sa.Float(), nullable=False),
    sa.Column('reputation', sa.Float(), nullable=False),
    sa.Column('season_points', sa.Integer(), nullable=False),
    sa.Column('shards', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_profiles')
    # ### end Alembic commands ###
